### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by longdx304** [longdx304/dob-outsourcing#4]
1) Our services:
- Hide nút Explora
- Mobile không hiển thị nội dung khi expand 
2) Case studies:
- Hide hàng nút Manufacture, Fintech, ..., Ecommerce
- Cập nhập hình và nội dung của 4 Case Studies
- Hide nút View the project 
- Mobile: Hide select dropdown, hiển thị luôn nội dung (bỏ motion)
3) Feedback:
- Cập nhập content 
4) Contact:
- Config email gửi về admin@dobtech.vn 
5) Cập nhập lại title bar và logo
6) Không vào được /en 
@thienduyy

**Comment by thienduyy** [comment]
Phần này e tạo PR rồi nha a
